version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www
        ports:
            - 8000:8000
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravelYoucef
            DB_USERNAME: root
            DB_PASSWORD: root

    db:
        image: mysql:8.0
        container_name: mysql_db
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: laravelYoucef
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
